### PR TITLE
feat: add `working_dir` argument for `external` data source

### PR DESCRIPTION
**Pull request by grv87**
Resubmitting https://github.com/hashicorp/terraform/pull/12144.
Implements #1

### CODE REVIEW

**Comment by grv87** [comment]
Note that this commit was exactly a year ago ))

**Comment by apparentlymart** [comment]
Thanks, @grv87!

**Comment by grv87** [comment]
Could you release version with this feature?

**Comment by rojopolis** [comment]
I'm in need of this feature as well.  How do features get released in this repo?  This was merged over 6 months ago!

**Comment by fingerco** [comment]
I dunno if this helps anyone, but I am using a temporary workaround:

```
# main.tf
data "external" "build" {
   program = ["bash", "${path.module}/build.sh"]

   query = {
     WORKING_DIR = "${path.module}"
   }
}
```

```
# bash.sh
WORKING_DIR=$(sed 's/{"WORKING_DIR":"\(.*\)"}/\1/' <&0)
```

**Pull request merged**
